//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoringDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuteeBusyTime
    {
        public int Id { get; set; }
        public int TuteeId { get; set; }
        public int BusyTimeId { get; set; }
    
        public virtual BusyTime BusyTime { get; set; }
        public virtual Tutee Tutee { get; set; }
    }
}
