//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoringDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorTuteeNotification
    {
        public int Id { get; set; }
        public Nullable<int> TutorId { get; set; }
        public Nullable<int> TuteeId { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
    
        public virtual Tutee Tutee { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
